AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: example # ファイル名
      Runtime: go1.x
      CodeUri: ../build # ビルドファイル設置ディレクトリ
      Timeout: 1
