name: Build
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Dependencies
      run: go mod download

    - name: Test
      run: make test

    - name: Build
      run: make all

    - name: Check builds
      run: ls -al build

    # - name: Setup Python 3.7 for awscli
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: '3.7'
    #     architecture: 'x64'
    # - name: Install awscli
    #   run: pip install --upgrade pip awscli
    # - name: Package cfn template
    #   run: |
    #     aws cloudformation package \
    #       --template-file cfn/application.yml \
    #       --s3-bucket cloudformation-package-bucket-packagebucket-1poq5xixcryds \
    #       --s3-prefix go-lambda-template \
    #       --output-template-file template.yml
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # - name: Deploy cfn template
    #   run: |
    #     aws cloudformation deploy \
    #       --stack-name go-lambda-template \
    #       --template-file template.yml \
    #       --capabilities CAPABILITY_IAM
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: ap-northeast-1
